require "checkpoints"
module Routes
  include Checkpoints

  def self.one
    [MINIMONKS, PHYLLIS, COBRA_LOUNGE, NICKS, ROOTS, DARKROOM, FIFTYFIFTY, MAHONEYS, FIVE_STAR, BOTTOM_LOUNGE, FINISH]
  end
  
  def self.two
    [MINIMONKS, PHYLLIS, COBRA_LOUNGE, NICKS, ROOTS, DARKROOM, FIFTYFIFTY, MAHONEYS, FIVE_STAR, BOTTOM_LOUNGE, FINISH].reverse
  end
  
end
